### ISSUE TITLE
Crash due to texture.properties

### ISSUE THREAD

**Issue by TheFurryDevil** [Null-MC/Create-PBR#1]
https://github.com/IrisShaders/Iris/issues/2033

Summary: I narrowed down a game crash to the `/assets/minecraft/optifine/texture.properties` in this pack.
I don't know what that file does but the textures seem to work without it, and removing it fixes the crash.

**Comment by null511** [comment]
Strange, that's a common file in any LabPBR pack and this issue's never been reported before.
