### ISSUE TITLE
Fluid pipes partial missing texture

### ISSUE THREAD

**Issue by 909oce** [Null-MC/Create-PBR#2]
![image](https://github.com/Null-MC/Create-PBR/assets/21692038/44070549-9d06-4bdd-bab0-3ec19eb2209b)
As you can see here, corner bending pipes seem to not be reflective or have a PBR texture, however the rest of the pipe does. I haven't looked into it too much yet, just thought I'd throw it in here aswell.

**Comment by 909oce** [comment]
![image](https://github.com/Null-MC/Create-PBR/assets/21692038/4bc3a85c-9162-4f93-9d43-d75c21ebe6cd)
Heres another image that shows a straight pipe also having a chunk of PBR missing in the center, or inconsistency in reflectiveness

**Comment by 909oce** [comment]
ignore my post. i finally looked at the texture files, turns out create changed its textures/paths for files in an update so half your resource pack has been broken and i didnt even notice lol

**Comment by steve-the-player** [comment]
They're still reflective, but the normals are messed up. I've been able to see this on pipe corners and fluid pumps. Belts might have it too, but it's so slight that it would be unnoticeable on a surface that isn't as reflective. The normals for the sides of the basin texture also appear to be shifted by two pixels. 
![2024-02-05_19 10 09](https://github.com/Null-MC/Create-PBR/assets/61434698/d13c0093-b924-45e7-8da3-890b5897d666)
It's easier to see with the "white world" shader mode
![2024-02-05_19 10 34](https://github.com/Null-MC/Create-PBR/assets/61434698/0504e722-b910-4ba9-8d8d-784fa6f9e057)

**Comment by null511** [comment]
Create has changed the UV layout for several blocks in the latest versions, so depending on which version you're using they might not match. And tbh I don't really want to try and maintain ~4 separate versions of this pack

**Comment by steve-the-player** [comment]
That’s completely fair, and it was what I imagined was going on. I might have a poke through the files in GIMP and see if I can’t rearrange stuff, if you’re ok with that

**Comment by null511** [comment]
long overdue but finally pushed a fix with updated UV's
